// Generated by CoffeeScript 1.6.2
var Fs, Path, emoji, emoji_folder, marked;

Fs = require('fs');

Path = require('path');

marked = require('marked');

emoji = require('emoji-images');

emoji_folder = Path.dirname(require.resolve('emoji-images')) + "/pngs";

module.exports = function(file, options, callback) {
  var _this = this;

  marked.setOptions(options);
  if (options.isFile) {
    return Fs.readFile(file, "utf8", function(err, data) {
      return callback(null, conversion(data));
    });
  } else {
    return callback(null, conversion(file));
  }
};

({
  conversion: function() {
    var emojified, mdToHtml;

    emojified = emoji(data, emoji_folder, 20);
    return mdToHtml = marked(emojified);
  }
});
